pipeline{
    
    agent any
    tools{
        maven 'Maven3'
    }
    stages{
        
        // stage('DeleteWS'){
        // steps{
        //     deleteDir()
        // }
            
        // }
        
        stage('Checkout'){
            
            steps{
            cleanWs() 
            checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'Mykey', url: 'https://github.com/harinipolina137/MYJavaApp']])
                 }
        }
        
        stage('Build'){
            
            steps{
                
               sh 'mvn clean install -f MyWebApp/pom.xml'
            }
        }
        
        stage('Deploy') {
            
            steps {
                
                sshagent(['deploy_user']) {
                    
               sh "scp -o StrictHostKeyChecking=no MyWebApp/target/MyWebApp.war ec2-user@18.204.215.202:/opt/apache-tomcat-9.0.73/webapps"
                
                // scp <src_file> username@IP:<dest_path>
                    
                       }
            }
        }
        
        stage('cleanup'){
            steps {
                
                cleanWs()
            }
            
        }
      
    }
    
}
